# Generated by Django 3.2.3 on 2021-07-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import stok.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0002_auto_20210515_1505'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('stockname', models.CharField(max_length=50)),
                ('birim', models.CharField(max_length=10)),
                ('materialtype', models.CharField(choices=[('AG.A1010', 'NVR-DVR'), ('AG.A1020', 'MONITOR'), ('AG.A1010', 'KAMERA')], max_length=15)),
                ('stocknumber', models.CharField(default='', max_length=15, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('Stok_Talebi', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.state')),
                ('creator', models.ForeignKey(default=1, on_delete=models.SET(stok.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
